# Generated by Django 6.0 on 2025-12-15 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='book_images')),
                ('text', models.FileField(upload_to='book_text')),
                ('authors', models.ManyToManyField(to='bookcontrol.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookcontrol.category')),
            ],
        ),
    ]
